let
    Source = CommonDataService.Database(CRM),
    dbo_lead = Source{[Schema="dbo",Item="lead"]}[Data],
    #"Changed Type" = Table.TransformColumnTypes(dbo_lead,{{"createdon", type date}, {"cra83_modifiedonfake", type date}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"createdon", "Fecha de Creación"}, {"cra83_modifiedonfake", "Fecha de Modificaciónf"}, {"industrycode", "Sector Industrial"}, {"leadqualitycode", "Rating"}, {"leadsourcecode", "Origen"}, {"statecode", "Estado"}, {"statuscode", "Razón Estado"}}),
    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns",{"leadid", "Fecha de Creación", "ownerid", "Sector Industrial", "Rating", "Origen", "numberofemployees", "revenue", "Estado", "Razón Estado", "cra83_productoid", "cra83_territoryid", "Fecha de Modificaciónf"}),
    #"Added Conditional Column" = Table.AddColumn(#"Removed Other Columns", "Tamaño", each if [numberofemployees] < 10 then 1 else if [numberofemployees] < 50 then 2 else if [numberofemployees] < 250 then 3 else if [numberofemployees] >= 250 then 4 else null, Int64.Type),
    #"Added Conditional Column1" = Table.AddColumn(#"Added Conditional Column", "Volumen", each if [revenue] <= 2000000 then 1 else if [revenue] <= 10000000 then 2 else if [revenue] <= 50000000 then 3 else if [revenue] <= 50000000 then 4 else null, Int64.Type),
    #"Added Custom" = Table.AddColumn(#"Added Conditional Column1", "Agging", each Duration.Days([Fecha de Modificaciónf]-[Fecha de Creación]), Int64.Type),
    #"Removed Other Columns1" = Table.SelectColumns(#"Added Custom",{"leadid", "Fecha de Creación", "ownerid", "Sector Industrial", "Rating", "Origen", "Estado", "Razón Estado", "cra83_productoid", "cra83_territoryid", "Fecha de Modificaciónf", "Tamaño", "Volumen", "Agging"})
in
    #"Removed Other Columns1"
